
-- Adds and offset to the camera pos and sets it as the curve center pos.

local curveworld = require "curveworld.curveworld"

go.property("camera_url", msg.url())

function init(self)
	self.offset = go.get_position()
	self.offset.y, self.offset.z = 0, 0
	curveworld.set_origin(0, 0, 0)
	curveworld.set_curve(0.005, 0.001)
end

function update(self, dt)
	local pos = go.get_position()
	local o = self.offset
	curveworld.set_origin(pos.x - o.x, pos.y - o.y, pos.z - o.z)
end
